[theme]
base="light"
primaryColor="#007BFF"  # A professional telecom blue (e.g., AT&T, Vodafone)
backgroundColor="#F0F2F6"  # Very light grey/blue, subtle background
secondaryBackgroundColor="#E0E7FF" # Lighter blue for secondary elements (e.g., sidebar, expanders)
textColor="#212529"      # Dark grey for main text for good readability
font="sans serif" 

